### ISSUE TITLE
Find a way to get rid of the __dirname when calling mocha(__dirname) and jasmine(__dirname)

### ISSUE THREAD

**Issue by staxmanade** [approvals/Approvals.NodeJS#5]
When you use approvals the require syntax is a bit annoying.

Instead of just `require('approvals').mocha()` we need to pass in the current directory of the testing file like `require('approvals').mocha(__dirname)`.

This is an annoying tax on each require to approvals and would be ideal to remove.

Not sure if anyone has any ideas on this, one might be to walk the stacktrace and see if we can get file/directory information from there.

**Comment by nathanbrock** [comment]
Greetings!

The resolution of this issue has introduced a breaking change since patch version [1.1.1](https://github.com/approvals/Approvals.NodeJS/releases/tag/v1.1.1). If using the parameter passed to the mocha/jasmine provider to reference a sub directory for approval files to be stored (like requested in issue #4), then this change breaks existing tests, forcing files to to be stored in the directory of the executing file.

*Example of previous use*
```javascript
approvals.mocha(__dirname + '/approvals');
```

Could it be considered, if passing a parameter as we did before commit 0456726d55358c46a7651c80fcb3c0afe4a65fe2, it will use that parameter and pass it to the [baseVerifier function](https://github.com/approvals/Approvals.NodeJS/blob/master/lib/Approvals.js#L99). If the parameter is ```null``` then it continues to use the callsite method currently in use to determine the tests directory.

Many thanks!

Nathan

**Comment by isidore** [comment]
yes, that's a better idea. we should preserve backward compatibility
whenever possible

Llewellyn Falco
www.approvaltests.com

**Comment by staxmanade** [comment]
Thanks @nathanbrock for bringing it up - will fix.

**Comment by staxmanade** [comment]
@nathanbrock mind having a quick look at `v1.1.2` and see how that works for you?

**Comment by nathanbrock** [comment]
@staxmanade that works great, many thanks!
